### ISSUE TITLE
Configuration File Documentation And Structure Updates

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#175]
### Proposal Description

Currently, there are only test configuration files and internal struct documentation provided. For the time being, this is OK. But in the feature, this will cause obvious problems. There 2 things to be done to solve this:

## Documentation

Clementine should have a user friendly documentation for configuration files, like markdown format. This can sit in `docs` directory.

## Sections

There is also one small obstacle against user friendliness: No sections. Currently configuration file looks very complicated because of this. Take this for example:

```toml
user_takes_after = 200
port = 3000
db_password = ""
secret_key = "5555555555555555555555555555555555555555555555555555555555555555"
confirmation_treshold = 1
db_port = 5432
verifiers_public_keys = [
    "4f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa",
    "466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27",
    "3c72addb4fdf09af94f0c94d7fe92a386a7e70cf8a1d85916386bb2535c7b1b1",
    "2c0b7cf95324a07d05398b240174dc0c2be444d96b159aa6c7f7b1e668680991",
    "9ac20335eb38768d2052be1dbbc3c8f6178407458e51e6b4ad22f1d91758895b",
]
db_user = "clementine"
num_verifiers = 4
tracing_debug = "debug,bitcoincore_rpc=info,hyper=error"
min_relay_fee = 305
host = "127.0.0.1"
network = "regtest"
bitcoin_rpc_url = "http://127.0.0.1:18443"
db_name = "clementine"
bitcoin_rpc_password = "admin"
all_secret_keys = [
    "1111111111111111111111111111111111111111111111111111111111111111",
    "2222222222222222222222222222222222222222222222222222222222222222",
    "3333333333333333333333333333333333333333333333333333333333333333",
    "4444444444444444444444444444444444444444444444444444444444444444",
    "5555555555555555555555555555555555555555555555555555555555555555",
]
db_host = "127.0.0.1"
bitcoin_rpc_user = "admin"
```

This example is intentionally mixed to show it can get very complicated. Even not intentionally modified, it can get still get this confusing by any cause.

To solve this issue, sections can be used. Same example with sections:

```toml
tracing_debug = "debug,bitcoincore_rpc=info,hyper=error"

num_verifiers = 4
min_relay_fee = 305
user_takes_after = 200
confirmation_treshold = 1

[operator-verifier]
host = "127.0.0.1"
port = 3000

[keys]
secret_key = "5555555555555555555555555555555555555555555555555555555555555555"
verifiers_public_keys = [
    "4f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa",
    "466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27",
    "3c72addb4fdf09af94f0c94d7fe92a386a7e70cf8a1d85916386bb2535c7b1b1",
    "2c0b7cf95324a07d05398b240174dc0c2be444d96b159aa6c7f7b1e668680991",
    "9ac20335eb38768d2052be1dbbc3c8f6178407458e51e6b4ad22f1d91758895b",
]
all_secret_keys = [
    "1111111111111111111111111111111111111111111111111111111111111111",
    "2222222222222222222222222222222222222222222222222222222222222222",
    "3333333333333333333333333333333333333333333333333333333333333333",
    "4444444444444444444444444444444444444444444444444444444444444444",
    "5555555555555555555555555555555555555555555555555555555555555555",
]

[bitcoin]
network = "regtest"
rpc_url = "http://127.0.0.1:18443"
rpc_user = "admin"
rpc_password = "admin"

[database]
host = "127.0.0.1"
port = 5432
user = "clementine"
password = ""
name = "clementine"
```

With sections, you can't mix members even if you wanted it: Parser will throw errors.

Of course, this is not a final proposal. Clementine also needs a stable interface for it's configuration. But it can be slowly implemented once a section is finalized. Database is one of the examples.
